### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [FauxFaux/bloboperations#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/goeswhere/bloboperations/HashedBlobStorage.java: Line number => 188: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR>

**Comment by FauxFaux** [comment]
Hello bot.

What?

There's no call by that name on that line. The updates happen in a different (standard) class, because this is Java code.
